//! `harness bench …` — benchmark suites (docs/SCHEMAS.md "M4 additions").
//!
//! A suite dir (e.g. `targets/tractor/`) holds `suite.toml`, `corpus.lock`,
//! one harness target per case under `cases/`, the held-out scoring material
//! under `heldout/`, and the committed `scores.json`.

use anyhow::{bail, Result};
use clap::Subcommand;
use harness_core::bench::{CorpusLock, Suite, SuiteCase};
use harness_core::driver::DriverValidation;
use harness_core::ledger::Ledger;
use harness_core::plan as plan_mod;
use harness_core::{attempts, hash, Facts, Plan, TargetContext};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

use crate::out;

#[derive(Subcommand)]
pub enum BenchCmd {
    /// Vendor the suite from a checkout of the pinned upstream commit and
    /// (re)write suite.toml's derived case list and corpus.lock
    Vendor {
        /// Suite dir (contains suite.toml)
        #[arg(long, default_value = ".")]
        suite: PathBuf,
        /// Upstream checkout, detached at the pinned commit
        #[arg(long)]
        from: PathBuf,
    },
    /// Verify every vendored file against corpus.lock
    VerifyCorpus {
        /// Suite dir (contains suite.toml)
        #[arg(long, default_value = ".")]
        suite: PathBuf,
    },
    /// Make every case a harness target: harness.toml, scan, plan, and the
    /// unit's [unit.oracle] table where absent (idempotent)
    Init {
        /// Suite dir (contains suite.toml)
        #[arg(long, default_value = ".")]
        suite: PathBuf,
        /// Report drift from freshly generated config/tables; write nothing
        #[arg(long)]
        check: bool,
    },
    /// Per-case pipeline progress from the case ledgers (no builds)
    Status {
        /// Suite dir (contains suite.toml)
        #[arg(long, default_value = ".")]
        suite: PathBuf,
    },
}

pub fn run(cmd: BenchCmd) -> Result<ExitCode> {
    match cmd {
        BenchCmd::Vendor { suite, from } => cmd_vendor(&suite, &from),
        BenchCmd::VerifyCorpus { suite } => cmd_verify_corpus(&suite),
        BenchCmd::Init { suite, check } => cmd_init(&suite, check),
        BenchCmd::Status { suite } => cmd_status(&suite),
    }
}

/// Load `suite.toml` and `corpus.lock` and require the corpus to verify.
pub fn load_verified(suite_dir: &Path) -> Result<(Suite, CorpusLock)> {
    let suite = Suite::load(&suite_dir.join("suite.toml"))?;
    let lock = CorpusLock::load(&suite_dir.join("corpus.lock"))?;
    lock.require_verified(suite_dir, &suite)?;
    Ok((suite, lock))
}

fn cmd_vendor(suite_dir: &Path, from: &Path) -> Result<ExitCode> {
    let suite = Suite::load(&suite_dir.join("suite.toml"))?;
    let (derived, lock) = harness_core::bench::vendor(suite_dir, &suite, from)?;
    derived.store(&suite_dir.join("suite.toml"))?;
    lock.store(&suite_dir.join("corpus.lock"))?;
    let violations = lock.verify(suite_dir, &derived)?;
    if !violations.is_empty() {
        bail!(
            "vendored tree does not verify ({} violation(s)); first: {}",
            violations.len(),
            violations[0]
        );
    }
    out(format!(
        "bench vendor: {} case(s), {} excluded, {} locked file(s) from {}@{}",
        derived.cases.len(),
        derived.excluded.len(),
        lock.files.len(),
        derived.upstream.tag,
        &derived.upstream.commit[..12]
    ));
    Ok(ExitCode::SUCCESS)
}

fn cmd_verify_corpus(suite_dir: &Path) -> Result<ExitCode> {
    let (suite, lock) = load_verified(suite_dir)?;
    out(format!(
        "bench verify-corpus: OK — {} locked file(s), {} case(s), {}@{}",
        lock.files.len(),
        suite.cases.len(),
        suite.upstream.tag,
        &suite.upstream.commit[..12]
    ));
    Ok(ExitCode::SUCCESS)
}

/// The generated `harness.toml` of a case (docs/SCHEMAS.md "M4 additions").
/// `include_dirs` lists `test_case/include` when the upstream case has one.
fn case_config(case: &SuiteCase, has_include: bool) -> String {
    let include = if has_include {
        "include_dirs = [\"test_case/include\"]\n"
    } else {
        ""
    };
    format!(
        "# Generated by `harness bench init` for suite case {path}.\n\
         # Regenerate rather than hand-edit (`harness bench init --check` reports drift).\n\
         schema_version = 1\n\n\
         [target]\n\
         name = \"{name}\"\n\
         source_dir = \"test_case\"\n\
         {include}\n\
         [oracle]\n\
         allowlist = [\"cc\", \"cargo\", \"rustc\", \"nm\"]\n\n\
         [llm]\n\
         provider = \"external\"\n\
         max_tokens = 16384\n",
        path = case.path,
        name = case.name(),
    )
}

fn cmd_init(suite_dir: &Path, check: bool) -> Result<ExitCode> {
    let (suite, _lock) = load_verified(suite_dir)?;
    let mut drift: Vec<String> = Vec::new();
    let mut failed: Vec<String> = Vec::new();
    let mut written = 0usize;
    for case in &suite.cases {
        let root = case.target_root(suite_dir);
        let has_include = root.join("test_case/include").is_dir();
        let config = case_config(case, has_include);
        let config_path = root.join("harness.toml");
        let current = std::fs::read_to_string(&config_path).ok();
        if current.as_deref() != Some(config.as_str()) {
            if check {
                drift.push(format!(
                    "{}: harness.toml differs from generated",
                    case.path
                ));
                continue;
            }
            harness_core::ledger::write_atomic(&config_path, config.as_bytes())?;
            written += 1;
        }
        if check {
            continue;
        }
        // A case the pipeline cannot take on (e.g. a frontend limitation) is
        // a FINDING: it stays in the suite and scores as not attempted.
        if let Err(e) = init_case(&root, case) {
            failed.push(format!("{}: {e:#}", case.path));
        }
    }
    if check {
        for d in &drift {
            out(format!("bench init --check: {d}"));
        }
        if !drift.is_empty() {
            return Ok(ExitCode::FAILURE);
        }
        out(format!(
            "bench init --check: {} case(s) match",
            suite.cases.len()
        ));
        return Ok(ExitCode::SUCCESS);
    }
    for f in &failed {
        out(format!("bench init: NOT initialized — {f}"));
    }
    out(format!(
        "bench init: {} of {} case(s) initialized ({written} harness.toml written); {} not \
         initialized (they stay in the suite and score as not attempted)",
        suite.cases.len() - failed.len(),
        suite.cases.len(),
        failed.len()
    ));
    Ok(ExitCode::SUCCESS)
}

/// Scan + plan one case target and give each unit its default oracle table.
fn init_case(root: &Path, case: &SuiteCase) -> Result<()> {
    let ctx = TargetContext::load(root)?;
    crate::scan_target(&ctx)?;
    crate::plan_target(&ctx)?;
    let ledger = Ledger::new(&ctx.root);
    let plan = Plan::load(&ledger.plan_path())?;
    // R3: the runner's symbol must be one the plan migrates.
    if !plan.units.iter().any(|u| u.symbols.contains(&case.symbol)) {
        bail!(
            "runner symbol `{}` is not a public symbol of any planned unit (the C frontend \
             found {} unit(s))",
            case.symbol,
            plan.units.len()
        );
    }
    for unit in &plan.units {
        plan_mod::set_oracle_table_if_absent(
            &ledger.plan_path(),
            &unit.id,
            &crate::gen_driver::default_oracle_entries(&unit.id, &unit.files),
        )?;
    }
    Ok(())
}

/// Driver state of a unit: `validated` (fresh green record), `stale`,
/// `failed` (record exists, red), or `missing`.
pub fn driver_state(
    ctx: &TargetContext,
    facts: &Facts,
    unit: &harness_core::Unit,
) -> Result<String> {
    let ledger = Ledger::new(&ctx.root);
    let path = ledger.driver_validation_path(&unit.id);
    if !path.exists() {
        return Ok("missing".into());
    }
    let v = DriverValidation::load(&path)?;
    if !v.green {
        return Ok("failed".into());
    }
    let closure = facts.include_closure(&unit.files);
    let unit_source = hash::file_set_hash_on_disk(&ctx.root, &closure)?;
    let driver_path = ledger.driver_path(&unit.id);
    let driver = if driver_path.exists() {
        hash::file_hash(&driver_path)?
    } else {
        String::new()
    };
    Ok(if v.is_fresh_green(&unit_source, &driver) {
        "validated".into()
    } else {
        "stale".into()
    })
}

fn cmd_status(suite_dir: &Path) -> Result<ExitCode> {
    let (suite, _lock) = load_verified(suite_dir)?;
    let mut tally: std::collections::BTreeMap<String, usize> = std::collections::BTreeMap::new();
    for case in &suite.cases {
        let root = case.target_root(suite_dir);
        let line = match case_status(&root) {
            Ok(s) => s,
            Err(e) => format!("error: {e:#}"),
        };
        *tally
            .entry(line.split(' ').next().unwrap_or("").to_string())
            .or_default() += 1;
        out(format!("{} [{}] {line}", case.path, case.split));
    }
    let summary: Vec<String> = tally.iter().map(|(k, v)| format!("{k}={v}")).collect();
    out(format!(
        "bench status: {} case(s): {}",
        suite.cases.len(),
        summary.join(" ")
    ));
    Ok(ExitCode::SUCCESS)
}

/// One case's pipeline line: `<unit-status> driver=<state> driver-attempts=N migrate-attempts=N (<last outcome>)`.
fn case_status(root: &Path) -> Result<String> {
    if !root.join("harness.toml").exists() {
        return Ok("uninitialized".into());
    }
    let ctx = TargetContext::load(root)?;
    let ledger = Ledger::new(&ctx.root);
    if !ledger.plan_path().exists() || !ledger.facts_path().exists() {
        return Ok("unplanned".into());
    }
    if Plan::load(&ledger.plan_path())?.units.is_empty() {
        return Ok("no-units (frontend found no unit)".into());
    }
    let facts = Facts::load(&ledger.facts_path())?;
    let plan = Plan::load(&ledger.plan_path())?;
    let mut parts = Vec::new();
    for unit in &plan.units {
        let d = attempts::load_unit_driver_attempts(&ledger, &unit.id)?;
        let m = attempts::load_unit_attempts(&ledger, &unit.id)?;
        let last = |v: &[attempts::AttemptRecord]| {
            v.last()
                .map(|r| r.outcome.clone())
                .unwrap_or_else(|| "-".into())
        };
        parts.push(format!(
            "{} {} driver={} driver-attempts={}({}) migrate-attempts={}({})",
            unit.status.as_str(),
            unit.id,
            driver_state(&ctx, &facts, unit)?,
            d.len(),
            last(&d),
            m.len(),
            last(&m)
        ));
    }
    Ok(parts.join("; "))
}
